Update validate-pr-title.yml

diff --git a/.github/workflows/validate-pr-title.yml b/.github/workflows/validate-pr-title.yml
--- a/.github/workflows/validate-pr-title.yml
+++ b/.github/workflows/validate-pr-title.yml
@@ -1,16 +1,30 @@
-name: PR Conventional Commit Validation
+name: Validate PR Title
 
 on:
   pull_request:
-    types: [opened, synchronize, reopened, edited]
+    types:
+      - opened
+      - synchronize
+      - edited
+      - labeled
+      - unlabeled
 
 jobs:
-  validate-pr-title:
+  Validate_PR_Title:
     runs-on: ubuntu-latest
     steps:
-      - name: PR Conventional Commit Validation
-        uses:  ytanikin/PRConventionalCommits@1.1.0
-        with:
-         task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
-         ticket_key_regex: '^PROJECT-\\d{2,5}$'
-         custom_labels: '{"feat": "feature", "fix": "fix", "docs": "documentation", "test": "test", "ci": "CI/CD", "refactor": "refactor", "perf": "performance", "chore": "chore", "revert": "revert", "wip": "WIP"}'
+      - name: Check PR title
+        if: github.event_name == 'pull_request'
+        run: |
+          pr_title="${{ github.event.pull_request.title }}"
+          
+          # Define the regex pattern for the PR title
+          PR_TITLE_PATTERN="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)\((account|inventory|general ledger)\): .+ \[([A-Z]+-\d+)\]$"
+          
+          if [[ ! "${pr_title}" =~ ${PR_TITLE_PATTERN} ]]; then
+            echo "error: invalid PR title format"
+            echo "Example: feat(account): Implement new feature [GCP-200]"
+            exit 1
+          fi
+
+          echo "PR title validation successful"
